services:
  mongo:
    image: mongo:8.0.1
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hrbs-network
    restart: always
  nodejs-server:
    build: .
    container_name: nodejs-server
    ports:
      - "3001:3001"
    volumes:
        - .:/app
    working_dir: /app
    networks:
      - hrbs-network
    depends_on:
      - mongo
    restart: always
networks:
    hrbs-network:
        driver: bridge
volumes:
    mongo-data:
      driver: local